language: swift
osx_image: xcode10

script:
- xcodebuild -project raye7Travis/raye7Travis.xcodeproj -scheme raye7Travis -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 7' clean build test

notifications:
    email:
        recipients:
            - ameguid12@gmail.com
        on_success: always # default: change
        on_failure: always # default: always
